version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file:
      - backend/.env.dev
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    env_file:
      - .env.local.dev
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "npm ci && npm run dev"
    depends_on:
      - api
