import { NextRequest, NextResponse } from 'next/server'

const DEMO: Record<string, any[]> = {
  photo: [
    { id: 'p1',  title: 'Midjourney Lifestyle Ads Pack (40 prompts)', slug: 'midjourney-lifestyle-ads', summary: 'High‑converting creative directions for lifestyle ads', modelTarget: 'Midjourney', priceUsd: '12.99', coverImage: 'https://images.unsplash.com/photo-1517167685282-9dfd7c2dc813?w=1200&q=60&auto=format&fit=crop', previewVideoUrl: null, category: { slug: 'photo', name: 'Photo' }, bestSeller: true, rating: 4.8, ratingCount: 128, views: 3245, salesCount: 612, tags: ['ads','lifestyle','social'], highlights: ['Optimized for CTR','Includes 12 styles','Printable & web-ready'], includes: ['Prompt template','Usage instructions','3 example outputs'] },
    { id: 'p2',  title: 'Stable Diffusion Product Shots Kit',       slug: 'sd-product-shots-kit',        summary: 'Studio‑quality product images with SD',         modelTarget: 'Stable Diffusion', priceUsd: '7.99',  coverImage: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=1200&q=60&auto=format&fit=crop', previewVideoUrl: null, category: { slug: 'photo', name: 'Photo' }, rating: 4.6, ratingCount: 86, views: 1820, salesCount: 301, tags: ['product','studio','ecommerce'], highlights: ['Shadow & reflection presets','Consistent angles'], includes: ['Prompt template','Lighting guide'] },
    { id: 'p3',  title: 'E‑commerce Pack: Background Remover',       slug: 'ecom-bg-remover',             summary: 'Clean product backgrounds in minutes',        modelTarget: 'Stable Diffusion', priceUsd: '4.99',  coverImage: 'https://images.unsplash.com/photo-1519337265831-281ec6cc8514?w=1200&q=60&auto=format&fit=crop', previewVideoUrl: null, category: { slug: 'photo', name: 'Photo' }, rating: 4.4, ratingCount: 55, views: 990, salesCount: 145, tags: ['bg','removal','ecommerce'], highlights: ['Batch‑ready prompts','White/transparent output'], includes: ['Prompt template'] },
    { id: 'p4',  title: 'Portrait Retouch Prompts',                   slug: 'portrait-retouch',            summary: 'Natural skin, eyes and lighting tweaks',      modelTarget: 'Midjourney',       priceUsd: '7.99',  coverImage: 'https://images.unsplash.com/photo-1544006659-f0b21884ce1d?w=1200&q=60&auto=format&fit=crop', previewVideoUrl: null, category: { slug: 'photo', name: 'Photo' }, rating: 4.7, ratingCount: 101, views: 2100, salesCount: 330, tags: ['portrait','retouch'], highlights: ['Skin & eyes presets','Subtle lighting fixes'], includes: ['Prompt template','Examples'] },
    { id: 'p5',  title: 'Brand Aesthetic Set (20 styles)',            slug: 'brand-aesthetic-set',         summary: 'Consistent brand look for campaigns',         modelTarget: 'Midjourney',       priceUsd: '12.99', coverImage: 'https://images.unsplash.com/photo-1517816743773-6e0fd518b4a6?w=1200&q=60&auto=format&fit=crop', previewVideoUrl: null, category: { slug: 'photo', name: 'Photo' }, rating: 4.9, ratingCount: 90, views: 2500, salesCount: 410, tags: ['brand','aesthetic'], highlights: ['20 presets','Unified styles'], includes: ['Prompt set','Usage tips'] },
    { id: 'p6',  title: 'Packshots Macros (SDXL)',                    slug: 'packshots-macros-sdxl',       summary: 'Sharp packshots with reflections',            modelTarget: 'Stable Diffusion', priceUsd: '7.99',  coverImage: 'https://images.unsplash.com/photo-1585386959984-a41552231658?w=1200&q=60&auto=format&fit=crop', previewVideoUrl: null, category: { slug: 'photo', name: 'Photo' }, rating: 4.5, ratingCount: 70, views: 1400, salesCount: 230, tags: ['macro','packshot'], highlights: ['Reflections presets'], includes: ['Prompt template'] },
    { id: 'p7',  title: 'Lifestyle Scene Generator',                  slug: 'lifestyle-scene-generator',   summary: 'Context scenes for your products',            modelTarget: 'Midjourney',       priceUsd: '12.99', coverImage: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1200&q=60&auto=format&fit=crop', previewVideoUrl: null, category: { slug: 'photo', name: 'Photo' }, rating: 4.6, ratingCount: 64, views: 1300, salesCount: 210, tags: ['lifestyle','scene'], highlights: ['Multiple backgrounds','Scale easily'], includes: ['Prompt set'] },
    { id: 'p8',  title: 'Lookbook Builder',                           slug: 'lookbook-builder',            summary: 'Series of coherent images for lookbooks',     modelTarget: 'Midjourney',       priceUsd: '7.99',  coverImage: 'https://images.unsplash.com/photo-1540574163026-643ea20ade25?w=1200&q=60&auto=format&fit=crop', previewVideoUrl: null, category: { slug: 'photo', name: 'Photo' }, rating: 4.3, ratingCount: 41, views: 800, salesCount: 120, tags: ['lookbook','series'], highlights: ['Coherent series'], includes: ['Prompt template'] },
    { id: 'p9',  title: 'UGC Photo Styles',                           slug: 'ugc-photo-styles',            summary: 'Authentic UGC‑style renderings',              modelTarget: 'Midjourney',       priceUsd: '4.99',  coverImage: 'https://images.unsplash.com/photo-1520975922284-9bcd5f9f4a49?w=1200&q=60&auto=format&fit=crop', previewVideoUrl: null, category: { slug: 'photo', name: 'Photo' }, rating: 4.2, ratingCount: 35, views: 700, salesCount: 95, tags: ['UGC','social'], highlights: ['Real-life look'], includes: ['Prompt template'] },
    { id: 'p10', title: 'Creative Backdrops (50 presets)',            slug: 'creative-backdrops-50',       summary: 'Backdrop presets for social shots',           modelTarget: 'Stable Diffusion', priceUsd: '12.99', coverImage: 'https://images.unsplash.com/photo-1483982258113-b72862e6cff6?w=1200&q=60&auto=format&fit=crop', previewVideoUrl: null, category: { slug: 'photo', name: 'Photo' }, rating: 4.7, ratingCount: 77, views: 1600, salesCount: 260, tags: ['backdrop','preset'], highlights: ['50 presets included'], includes: ['Prompt pack'] },
  ],
  video: [
    { id: 'v1', title: 'YouTube Shorts Hooks (100 prompts)', slug: 'yt-shorts-hooks', summary: 'Hooks and outlines for viral Shorts', modelTarget: 'GPT-4', priceUsd: '12.99', coverImage: null, previewVideoUrl: 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4', category: { slug: 'video', name: 'Video' }, bestSeller: true, rating: 4.9, ratingCount: 210, views: 5400, salesCount: 950, tags: ['shorts','hooks','reels'], highlights: ['100+ hooks','A/B variants','Viral patterns'], includes: ['Prompt pack','Usage cheatsheet'] },
    { id: 'v2', title: 'Video Script Beats (AIDA/PASTOR)',    slug: 'video-script-beats', summary: 'Structure any ad or explainer video', modelTarget: 'GPT-4', priceUsd: '11.00', coverImage: null, previewVideoUrl: null, category: { slug: 'video', name: 'Video' }, rating: 4.6, ratingCount: 120, views: 3100, salesCount: 500, tags: ['script','aida','pastor'], highlights: ['Reusable beats','Clear rhythm'], includes: ['Prompt template'] },
    { id: 'v3', title: 'Reels Caption Generator',             slug: 'reels-caption',      summary: 'Catchy captions with CTAs',         modelTarget: 'GPT-4', priceUsd: '6.99',  coverImage: null, previewVideoUrl: null, category: { slug: 'video', name: 'Video' }, rating: 4.5, ratingCount: 80, views: 2100, salesCount: 340, tags: ['reels','caption'], highlights: ['Scroll‑stopping hooks'], includes: ['Prompt list'] },
    { id: 'v4', title: 'Storyboards from Product Page',       slug: 'storyboard-from-plp', summary: 'Generate scenes from a URL',     modelTarget: 'GPT-4', priceUsd: '9.00',  coverImage: null, previewVideoUrl: null, category: { slug: 'video', name: 'Video' }, rating: 4.4, ratingCount: 64, views: 1750, salesCount: 260, tags: ['storyboard','scenes'], highlights: ['URL → shots'], includes: ['Prompt template'] },
    { id: 'v5', title: 'Hook Library for TikTok',             slug: 'tiktok-hook-library', summary: 'Top 120 hooks sorted by niche', modelTarget: 'GPT-4', priceUsd: '8.99',  coverImage: null, previewVideoUrl: null, category: { slug: 'video', name: 'Video' }, rating: 4.3, ratingCount: 48, views: 1200, salesCount: 180, tags: ['tiktok','hooks'], highlights: ['120 hooks','By niche'], includes: ['Prompt pack'] },
    { id: 'v6', title: 'Promo VO Lines (Male/Female)',        slug: 'promo-vo-lines',     summary: 'Voice over lines for promos',     modelTarget: 'GPT-4', priceUsd: '5.00',  coverImage: null, previewVideoUrl: null, category: { slug: 'video', name: 'Video' }, rating: 4.2, ratingCount: 33, views: 800, salesCount: 110, tags: ['voice','promo'], highlights: ['Male/Female options'], includes: ['Prompt list'], author: 'Studio Vox', description: 'Generate promo-ready voice-over lines with variants for male and female voices. Ideal for ads, trailers and product videos.' },
    { id: 'v7', title: 'B‑roll Ideas Generator',              slug: 'broll-ideas',        summary: 'B‑roll shot list by theme',       modelTarget: 'GPT-4', priceUsd: '7.00',  coverImage: null, previewVideoUrl: null, category: { slug: 'video', name: 'Video' }, rating: 4.4, ratingCount: 52, views: 1000, salesCount: 150, tags: ['b-roll','ideas'], highlights: ['Shot lists'], includes: ['Prompt list'] },
  ],
  marketing: [
    { id: 'm1', title: 'Ad Script Generator',          slug: 'ad-script-generator',     summary: 'Ad scripts for FB/IG/TikTok',       modelTarget: 'GPT-4 / Claude', priceUsd: '11.99', coverImage: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&q=60&auto=format&fit=crop', previewVideoUrl: null, category: { slug: 'marketing', name: 'Marketing' }, rating: 4.7, ratingCount: 140, views: 4200, salesCount: 620, tags: ['ads','scripts'], highlights: ['Frameworks built‑in','Hooks & CTAs'], includes: ['Prompt templates'] },
    { id: 'm2', title: 'SEO Brief Builder',            slug: 'seo-brief-builder',       summary: 'Brief + outline + FAQs',            modelTarget: 'GPT-4',           priceUsd: '9.99',  coverImage: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=1200&q=60&auto=format&fit=crop', previewVideoUrl: null, category: { slug: 'marketing', name: 'Marketing' }, rating: 4.6, ratingCount: 110, views: 3000, salesCount: 530, tags: ['seo','content'], highlights: ['SERP‑first briefs','FAQs'], includes: ['Prompt template'] },
    { id: 'm3', title: 'Newsletter Composer',          slug: 'newsletter-composer',     summary: 'Weekly campaign newsletter',        modelTarget: 'GPT-4',           priceUsd: '7.00',  coverImage: null, previewVideoUrl: null, category: { slug: 'marketing', name: 'Marketing' }, rating: 4.3, ratingCount: 60, views: 1200, salesCount: 200, tags: ['newsletter'], highlights: ['Consistent tone'], includes: ['Prompt template'] },
    { id: 'm4', title: 'Product Hunt Launch Kit',      slug: 'ph-launch-kit',           summary: 'Copy blocks for PH launch',         modelTarget: 'GPT-4',           priceUsd: '10.00', coverImage: null, previewVideoUrl: null, category: { slug: 'marketing', name: 'Marketing' }, rating: 4.4, ratingCount: 75, views: 1500, salesCount: 260, tags: ['producthunt','launch'], highlights: ['Maker‑friendly plan'], includes: ['Prompt pack'] },
    { id: 'm5', title: 'LinkedIn Carousel Writer',     slug: 'linkedin-carousel',       summary: 'Carousel posts with hook slides',   modelTarget: 'GPT-4',           priceUsd: '8.99',  coverImage: 'https://images.unsplash.com/photo-1526378722484-bd91ca387e72?w=1200&q=60&auto=format&fit=crop', previewVideoUrl: null, category: { slug: 'marketing', name: 'Marketing' }, rating: 4.5, ratingCount: 84, views: 1800, salesCount: 300, tags: ['linkedin','carousel'], highlights: ['Hook slide patterns'], includes: ['Prompt template'] },
    { id: 'm6', title: 'UGC Briefs for Creators',      slug: 'ugc-briefs',              summary: 'Clear briefs for paid UGC',         modelTarget: 'GPT-4',           priceUsd: '6.00',  coverImage: null, previewVideoUrl: null, category: { slug: 'marketing', name: 'Marketing' }, rating: 4.2, ratingCount: 38, views: 900, salesCount: 130, tags: ['ugc','briefs'], highlights: ['Creator‑ready structure'], includes: ['Prompt template'] },
    { id: 'm7', title: 'Cold Email Personalizer',      slug: 'cold-email-personalizer', summary: '1‑to‑1 personalization at scale',  modelTarget: 'GPT-4',           priceUsd: '9.99',  coverImage: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=1200&q=60&auto=format&fit=crop', previewVideoUrl: null, category: { slug: 'marketing', name: 'Marketing' }, rating: 4.6, ratingCount: 96, views: 2400, salesCount: 420, tags: ['cold email','personalization'], highlights: ['Ice‑breakers','Follow‑ups'], includes: ['Prompt pack'] },
  ],
}

export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url)
  const category = searchParams.get('category') || 'photo'
  const limit = parseInt(searchParams.get('limit') || '24', 10)
  const items = (DEMO[category] || []).slice(0, Math.max(1, Math.min(limit, 100)))
  return NextResponse.json({ items })
}


