import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

// This script will add more automation and workflow AI tools to the database
async function updateOrCreateProducts() {
  console.log('Saving automation and workflow AI tools (batch 4) to database...')

  // Array of automation and workflow products to add or update
  const automationProducts = [
    {
      externalUrl: "https://www.powerautomate.microsoft.com",
      data: {
        name: "Microsoft Power Automate",
        description: "Cloud-based service with AI capabilities that helps create automated workflows between apps and services to synchronize files, get notifications, and collect data.",
        price: 180,
        category: "automation",
        imageUrl: "https://powerautomate.microsoft.com/images/application-logos/svg/powerautomate.svg",
        tags: "workflow automation, Microsoft integration, low-code, RPA, business process",
        advantages: "Seamless Microsoft ecosystem integration, Low-code/no-code interface, AI Builder for intelligent automation, Both cloud and desktop automation, Extensive connector library",
        disadvantages: "Full capabilities require premium licensing, Complex flows have learning curve, Limited customization for complex scenarios, UI flows require Windows, Performance depends on connection reliability",
        detailInfo: "Microsoft Power Automate (formerly Flow) is a versatile automation platform that enables users to create workflows across multiple applications and services without the need for developer expertise. The platform offers four key types of flows: automated flows triggered by specific events, instant flows activated manually, scheduled flows that run at designated times, and business process flows that provide guided experiences. At the heart of Power Automate is its intuitive visual designer that allows users to build workflows using a drag-and-drop interface, connecting various actions and triggers through logical steps. The platform includes AI Builder capabilities that bring intelligence to automations by incorporating pre-built AI models for tasks like form processing, object detection, text analysis, and prediction. For desktop-based tasks, Power Automate Desktop extends automation capabilities to legacy applications and manual processes through robotic process automation (RPA), allowing users to record and automate repetitive tasks across desktop applications. A major strength of Power Automate is its extensive connector library, with over 800 pre-built connectors to popular services (SharePoint, Dynamics 365, Office 365, Salesforce, etc.) and custom API connections for proprietary systems. The platform includes advanced features for error handling, expressions, conditions, and loops, enabling sophisticated workflow logic while maintaining a low-code approach. Power Automate offers comprehensive monitoring and management capabilities, allowing users to track runs, troubleshoot issues, and optimize performance through built-in analytics. The solution is designed for various use cases ranging from simple personal productivity enhancements to complex enterprise-wide business processes requiring formal approvals, data validation, and multi-stage workflows. Power Automate serves users across organizations of all sizes and industries, from individual business users automating routine tasks to IT professionals implementing company-wide automation strategies.",
        pricingInfo: "Microsoft Power Automate offers multiple licensing options to accommodate different user needs and organization sizes. The per-user plan costs $15 per user per month and provides licensed individuals with unlimited flow runs (within service limits) for attended RPA, access to AI Builder capabilities, and the ability to create unlimited flows. The per-flow plan starts at $100 per flow per month (with a minimum purchase of 5 flows) and allows unlimited users within the organization to access these flows, making it ideal for widely used department or company processes. For organizations requiring desktop automation, Power Automate Desktop is included with Windows 10/11, but attended and unattended RPA scenarios require additional licensing. Power Automate also offers a free tier with basic functionality, including 5,000 runs per month and access to standard connectors, making it suitable for personal productivity and learning. The solution includes add-ons for specific needs, such as AI Builder capacity (starting at $500 per month) for intelligent document processing and other AI-powered capabilities. Most enterprise customers access Power Automate as part of broader Microsoft 365 or Power Platform licensing, with varying capabilities depending on the specific license level. Volume discounting is available for enterprise agreements, and educational and non-profit organizations qualify for special pricing.",
        videoUrls: "https://www.youtube.com/watch?v=hCuxuUaGC6Y",
        hasTrial: true
      }
    },
    {
      externalUrl: "https://www.otio.ai",
      data: {
        name: "Otio",
        description: "AI workflow automation tool that helps teams create, visualize, and execute processes with natural language instructions and no-code building blocks.",
        price: 480,
        category: "automation",
        imageUrl: "https://otio.io/wp-content/themes/otio/images/otio-logo.svg",
        tags: "natural language workflow, visual automation, collaboration, process management, team productivity",
        advantages: "Natural language process creation, Visual workflow canvas, Real-time collaboration, Process template library, Integration with business tools",
        disadvantages: "Newer platform with growing ecosystem, Limited advanced customization, Enterprise features require higher tier plans, Best with established tech stack, Learning curve for complex processes",
        detailInfo: "Otio is an innovative workflow automation platform that enables teams to create, visualize, and execute business processes using natural language instructions and visual building blocks. The platform reimagines how workflows are designed by allowing users to describe processes in everyday language, which Otio's AI then transforms into structured, executable workflows. At the core of Otio is its dual-mode interface that combines natural language processing with visual design. Users can start by typing instructions like 'When a new lead is created in Salesforce, send a welcome email and notify the sales team,' and the system automatically generates a workflow diagram with the appropriate steps and connections. This initial structure can then be refined using the visual editor, which provides a drag-and-drop canvas for adding conditions, loops, and additional actions. Otio's collaborative features enable multiple team members to work on processes simultaneously, with real-time updates, commenting, and version control that maintain process integrity while facilitating input from stakeholders across departments. The platform includes a comprehensive template library covering common business processes across marketing, sales, HR, and operations, allowing teams to start with proven workflows rather than building from scratch. A key differentiator is Otio's focus on process visibility and documentation, with automatically generated documentation that explains each step of the workflow in clear language and maintains an audit trail of process changes and executions. Otio connects with popular business applications through a growing library of pre-built integrations and webhooks, enabling workflows to span across tools like CRM systems, marketing platforms, project management tools, and communication channels. The platform includes robust error handling and notification systems that alert teams to issues and provide debugging tools to quickly identify and resolve workflow problems. Otio serves customers across industries with particular appeal to mid-sized organizations undergoing digital transformation or seeking to standardize and scale their operational processes without extensive IT resources.",
        pricingInfo: "Otio offers tiered pricing based on features, workflow complexity, and user requirements. The Basic plan costs $40 per month (billed annually at $480) for up to 5 users and includes core functionality such as natural language workflow creation, visual editing, basic integrations, and standard support. The Professional plan at $100 per month (billed annually at $1,200) supports up to 10 users and adds advanced features including conditional workflows, advanced integrations, analytics, and priority support. The Enterprise plan with custom pricing provides unlimited users and premium capabilities such as dedicated account management, custom integrations, enhanced security controls, and professional services for implementation and training. All plans include unlimited workflows within reasonable usage limits. Otio offers a 14-day free trial across all plans, allowing teams to evaluate the platform without commitment. The company provides monthly billing options at approximately 25% higher rates than annual commitments. For larger organizations, volume discounts are available on annual subscriptions. Educational institutions and non-profit organizations can request special pricing and extended trial periods.",
        videoUrls: "https://www.youtube.com/watch?v=OlVBQvDjz5A",
        hasTrial: true
      }
    },
    {
      externalUrl: "https://www.cflowapps.com",
      data: {
        name: "cflow",
        description: "AI-enhanced workflow automation platform that digitizes business processes and approval workflows with form-based automation and process intelligence.",
        price: 540,
        category: "automation",
        imageUrl: "https://cflowapps.com/wp-content/uploads/2017/07/cflow-logo-1.png",
        tags: "workflow automation, form automation, approval management, business process, document workflow",
        advantages: "User-friendly form builder, Flexible approval routing, Mobile workflow access, Process analytics and insights, Document handling and e-signatures",
        disadvantages: "Limited advanced integrations, Basic UI compared to newer platforms, Custom development requires higher tier, More complex setup for advanced workflows, Limited AI capabilities in lower tiers",
        detailInfo: "cflow is a comprehensive workflow automation platform designed to digitize, streamline, and manage business processes with a focus on approval workflows and form-based automation. The platform enables organizations to replace paper-based processes and email approvals with structured digital workflows that enhance efficiency, transparency, and compliance. At the heart of cflow is its intuitive form builder, which allows users to create custom forms with various field types, validation rules, conditional logic, and formatting options. These forms serve as the front end for workflow initiation, data collection, and process tracking. The platform's workflow engine supports both simple sequential workflows and complex conditional routing based on form data, user roles, organizational hierarchy, or custom business rules. A key strength of cflow is its approval management system, which provides flexible options for routing items to approvers including serial approvals, parallel approvals, conditional approvals, and delegation mechanisms. The platform includes document management capabilities that allow workflows to incorporate electronic documents, generate PDFs from form data, support e-signatures, and maintain a secure document repository with version control. cflow's reporting and analytics module provides insights into process performance, bottlenecks, turnaround times, and user productivity through customizable dashboards and scheduled reports. The platform offers multi-device accessibility with responsive web design and mobile applications, ensuring users can participate in workflows from anywhere. cflow includes role-based access controls and audit trails that support compliance requirements by tracking every action, decision, and modification within workflows. While primarily focused on internal process automation, the platform also offers customer-facing portals where external stakeholders can submit requests and track their status. cflow serves organizations across industries including manufacturing, healthcare, professional services, and education, with particular strength in use cases such as purchase requisitions, expense approvals, leave management, IT service requests, and contract reviews.",
        pricingInfo: "cflow offers tiered pricing based on user count, features, and deployment options. The Business plan costs $45 per month (billed annually at $540) for up to 10 users and includes core features like workflow creation, form building, basic reporting, and standard support. The Enterprise plan at $90 per month (billed annually at $1,080) supports up to 20 users and adds advanced features including conditional workflows, API access, advanced reporting, and priority support. The Enterprise Plus plan with custom pricing provides support for larger user bases and premium capabilities such as dedicated account management, advanced security features, custom integrations, and white-labeling options. For organizations requiring on-premises deployment or private cloud instances, cflow offers special licensing models starting at $5,000 for perpetual licenses plus annual maintenance. The platform provides a 14-day free trial of paid plans and offers a limited free tier supporting up to 3 users and 5 workflows for small teams or evaluation purposes. Additional users can be added to any plan at a rate of approximately $3-$5 per user per month depending on volume. Implementation services and training packages are available as add-ons, with pricing based on scope and complexity.",
        videoUrls: "https://www.youtube.com/watch?v=jrFQZWtf5cY",
        hasTrial: true
      }
    },
    {
      externalUrl: "https://www.meistertask.com",
      data: {
        name: "MeisterTask",
        description: "AI-supported project and task management platform with automated workflows and smart features for team collaboration and productivity.",
        price: 108,
        category: "automation",
        imageUrl: "https://www.meistertask.com/images/meistertask-logo.svg",
        tags: "task management, project collaboration, kanban boards, workflow automation, team productivity",
        advantages: "Intuitive, visually appealing interface, Automation rules for recurring tasks, Native time tracking, MindMeister mind map integration, File attachments and comments",
        disadvantages: "Limited reporting in lower tiers, Fewer integrations than competitors, Basic automation features, No Gantt or timeline views, Mobile app with limited functionality",
        detailInfo: "MeisterTask is a visually oriented task and project management platform designed to help teams collaborate effectively and streamline workflows through intuitive Kanban-style boards. The platform combines simplicity with powerful automation capabilities to make project management accessible while providing the tools needed for effective work coordination. At the core of MeisterTask is its project board interface, where tasks move through customizable sections representing workflow stages (e.g., Open, In Progress, Review, Done). Each project can have its own unique board configuration reflecting its specific workflow requirements. Tasks within MeisterTask can contain rich details including descriptions, checklists, attachments, due dates, time tracking, tags, and custom fields, providing comprehensive information without overwhelming complexity. The platform's automation engine allows teams to create rules that trigger actions when tasks enter specific sections, such as automatically assigning team members, adding tags, setting due dates, or sending notifications, reducing manual administrative work. A unique feature is MeisterTask's integration with MindMeister, allowing teams to brainstorm ideas in a mind map and then convert them directly into actionable tasks, creating a seamless workflow from concept to execution. The platform includes collaboration features such as @mentions, comments with markdown support, watch functionality for task updates, and task relationships to track dependencies and connected work. MeisterTask offers time tracking capabilities that enable team members to record time spent on tasks directly within the platform, generating reports for billing, capacity planning, and productivity analysis. The platform integrates with popular tools including Slack, Microsoft Teams, GitHub, Zendesk, and various calendar applications, connecting MeisterTask with existing workflow systems. MeisterTask serves customers across industries including marketing agencies, software development teams, creative studios, and professional services organizations, with particular appeal to teams seeking a visually intuitive alternative to complex project management solutions.",
        pricingInfo: "MeisterTask offers tiered pricing based on features and capabilities. The Basic plan is free and supports up to 3 projects with limited task management features, suitable for individuals or small teams getting started with the platform. The Pro plan costs $9 per user per month (billed annually at $108 per user) and includes unlimited projects, automation rules, file attachments, and reporting capabilities. The Business plan at $18 per user per month (billed annually at $216 per user) adds advanced features including roles and permissions, custom fields, priority support, and advanced project management tools. The Enterprise plan with custom pricing includes premium features such as dedicated account management, single sign-on, custom security controls, and enhanced compliance capabilities. All paid plans offer a 30-day free trial period. MeisterTask provides monthly billing options at approximately 25% higher rates than annual commitments. For educational institutions, the platform offers MeisterTask EDU with discounted pricing and special features tailored to classroom usage. Non-profit organizations can request discounts through MeisterTask's NPO program.",
        videoUrls: "https://www.youtube.com/watch?v=eeYAC8eXlvI",
        hasTrial: true
      }
    },
    {
      externalUrl: "https://www.n8n.io",
      data: {
        name: "n8n",
        description: "Open-source workflow automation platform with AI capabilities that connects apps, databases, and services with a powerful, flexible node-based approach.",
        price: 240,
        category: "automation",
        imageUrl: "https://n8n.io/images/n8n-logo.svg",
        tags: "workflow automation, open source, API integration, no-code, data processing",
        advantages: "Open-source flexibility and transparency, Self-hosted option for data privacy, Powerful node-based workflow editor, Fair-code licensing model, Full control over data flows",
        disadvantages: "Steeper learning curve than some alternatives, Technical setup for self-hosting, Community nodes vary in quality, Enterprise features require paid cloud version, Limited visual styling options",
        detailInfo: "n8n (pronounced 'n-eight-n') is a flexible workflow automation platform that enables users to connect different systems and automate data flows between them using a powerful node-based approach. As an open-source solution, n8n offers unique flexibility and transparency compared to proprietary alternatives, while maintaining accessibility through its visual workflow editor. At the heart of n8n is its workflow editor, which provides a canvas where users connect nodes representing different services, triggers, and operations. Each node encapsulates specific functionality—from simple API requests to complex data transformations—and can be configured through an intuitive interface without requiring coding knowledge, though JavaScript expressions can be used for advanced customization. The platform includes over 300 pre-built nodes for popular services including CRM systems, databases, email providers, payment processors, and social media platforms, with new integrations regularly added by both the core team and community contributors. A key differentiator is n8n's flexible deployment model, offering both cloud-hosted and self-hosted options. The self-hosted version allows organizations to keep sensitive data within their infrastructure and customize the platform to meet specific requirements, while the cloud version provides convenience and managed infrastructure. n8n excels at data processing capabilities, with nodes for operations like filtering, mapping, merging, and transforming data between different systems, making it particularly valuable for integration scenarios requiring data manipulation. The platform supports various trigger mechanisms including webhooks, scheduled events, manual execution, and real-time monitoring of data sources, enabling both event-driven and time-based automation. The n8n ecosystem includes a vibrant community that contributes additional nodes, workflows, and documentation, extending the platform's capabilities beyond the core offering. Advanced features include error handling, branching logic, looping operations, and workflow history, providing the tools needed for complex automation scenarios. n8n serves users ranging from individual developers and small businesses to large enterprises, with particular appeal to organizations with technical capabilities or privacy requirements that benefit from the self-hosted option.",
        pricingInfo: "n8n offers multiple pricing options to accommodate different user needs and organization types. The n8n.cloud service provides a managed cloud solution with tiered pricing. The Starter plan costs $20 per month (billed annually at $240) and includes 3 users, 10 active workflows, standard nodes, community support, and basic security features. The Professional plan at $99 per month (billed annually at $1,188) supports 5 users, 25 active workflows, and adds features including team collaboration, workflow sharing, and priority support. The Enterprise plan with custom pricing provides unlimited users, workflows, and premium features such as dedicated support, custom security controls, and service level agreements. For self-hosting, n8n is available under a fair-code license that allows free use for individuals and small teams. Larger organizations using self-hosted n8n in production environments require an Enterprise Self-Hosted license with pricing based on scale and support requirements, typically starting at several thousand dollars annually. The platform offers a 14-day free trial of cloud plans and a free community edition for self-hosting with limited features. Educational institutions and non-profit organizations can request special pricing for cloud plans or licensing exemptions for self-hosted deployments.",
        videoUrls: "https://www.youtube.com/watch?v=1MwSoB0gnM4",
        hasTrial: true
      }
    },
    {
      externalUrl: "https://www.albato.com",
      data: {
        name: "Albato",
        description: "No-code integration platform with AI capabilities that connects applications and automates data flows between business tools and services.",
        price: 360,
        category: "automation",
        imageUrl: "https://albato.com/icons/logo-albato.svg",
        tags: "data integration, workflow automation, API connection, no-code integration, SaaS connectors",
        advantages: "User-friendly no-code interface, Extensive app library with 600+ integrations, Real-time and batch data processing, Ready-to-use integration templates, Pay-per-use pricing option",
        disadvantages: "Limited advanced customization, Newer platform with growing ecosystem, Complex transformations require formulas, Enterprise features in higher tiers only, Documentation less comprehensive than established platforms",
        detailInfo: "Albato is a modern integration platform that enables businesses to connect their applications and automate data flows without coding knowledge. The platform focuses on simplicity and accessibility while providing the power to handle complex integration scenarios across marketing, sales, finance, and operations functions. At the core of Albato is its intuitive visual builder, which allows users to create automated workflows (called 'connections') by defining triggers that initiate the process and actions that execute in response. The platform supports various trigger types including data changes, form submissions, scheduled events, and webhooks, enabling both event-driven and time-based automation. Albato offers an extensive library of over 600 pre-built connectors for popular business applications spanning categories such as CRM, marketing automation, e-commerce, accounting, project management, and communication tools. Each connector is maintained by the Albato team to ensure reliability as underlying APIs evolve. The platform includes powerful data transformation capabilities that allow users to map fields between applications, apply formulas and conditions, format data, and handle arrays and complex objects, ensuring information flows correctly between systems with different data structures. A key feature is Albato's ready-to-use templates for common integration scenarios (e.g., syncing customers between CRM and email platforms, connecting e-commerce stores with accounting systems), which users can implement with minimal configuration. The platform provides comprehensive monitoring tools that track execution history, visualize data flows, and alert users to errors or anomalies, facilitating troubleshooting and optimization. Albato emphasizes data security with end-to-end encryption, role-based access controls, and compliance with major regulations, addressing common concerns about integration platforms handling sensitive business data. The platform serves businesses of all sizes, from small companies looking to eliminate manual data entry to enterprises requiring complex multi-directional integrations between numerous systems, with particular strength in marketing technology stacks, e-commerce operations, and sales-to-finance workflows.",
        pricingInfo: "Albato offers flexible pricing options designed to accommodate different integration needs and organizational sizes. The Starter plan costs $30 per month (billed annually at $360) and includes 3 active connections, 1,000 operations per month, basic support, and access to the full connector library. The Professional plan at $99 per month (billed annually at $1,188) provides 10 active connections, 10,000 operations monthly, priority support, and additional features like advanced transformations and error handling. The Business plan at $299 per month (billed annually at $3,588) supports 30 active connections, 100,000 operations, dedicated support, and enterprise features including team collaboration and advanced security controls. For organizations with variable or high-volume needs, Albato offers a consumption-based pricing model where customers purchase operation packs (starting at $0.001-$0.005 per operation depending on volume) and pay only for what they use. Implementation services, including custom connector development and integration consulting, are available at additional cost, typically ranging from $1,000-$5,000 depending on complexity. Albato provides a 14-day free trial of all plans and offers limited free tier access with 1 connection and 100 operations monthly for evaluation purposes. Monthly billing options are available at approximately 20% higher rates than annual commitments.",
        videoUrls: "https://www.youtube.com/watch?v=xHIzXKCQdRk",
        hasTrial: true
      }
    },
    {
      externalUrl: "https://www.pabbly.com/connect",
      data: {
        name: "Pabbly Connect",
        description: "Cost-effective workflow automation tool with AI integration capabilities that connects apps and automates tasks with unlimited workflows and users.",
        price: 588,
        category: "automation",
        imageUrl: "https://cdn.pabbly.com/wp-content/uploads/2022/06/11022833/connect-logo.png",
        tags: "workflow automation, SaaS integration, API connectivity, unlimited workflows, data synchronization",
        advantages: "Unlimited workflows and tasks on all plans, Single subscription price regardless of user count, No transaction fees or operation limits, Private workflows and team sharing, Competitive pricing compared to alternatives",
        disadvantages: "Smaller connector library than market leaders, Limited enterprise security features, Fewer advanced conditional options, Basic UI compared to premium tools, Smaller community for support",
        detailInfo: "Pabbly Connect is a workflow automation platform designed to help businesses connect their applications and automate repetitive tasks with a focus on unlimited usage and cost-effectiveness. The platform differentiates itself from competitors by removing common restrictions like workflow limits, user caps, and transaction fees, providing predictable pricing regardless of automation scale. At the heart of Pabbly Connect is its workflow builder, which uses a trigger-action model to create automated processes between various applications. Users can define triggers that initiate workflows (such as new form submissions, updated records, or scheduled events) and chain together multiple actions across different applications. The platform offers 1,000+ app integrations covering major categories including CRM, email marketing, e-commerce, forms, payment processing, and project management, enabling connectivity between popular business tools. Pabbly Connect includes data transformation capabilities that allow users to map fields between applications, apply filters based on conditions, format data, and handle various data types and structures. The platform supports multi-step workflows with conditional branching, allowing different actions to execute based on specific criteria and creating dynamic processes that adapt to different scenarios. A key feature is Pabbly's support for custom webhooks and HTTP requests, enabling integration with applications that don't have pre-built connectors or with proprietary internal systems. The platform provides workflow monitoring and logging tools that track execution history, success rates, and error details, facilitating troubleshooting and optimization. Pabbly Connect emphasizes team collaboration with features that allow workflows to be shared with team members, enabling cooperative development and management of automation across departments. The platform serves businesses of all sizes, from solopreneurs and small businesses attracted by the unlimited usage model to larger organizations looking for cost-effective automation at scale, with particular appeal to marketing agencies, e-commerce operations, and SMBs with limited IT resources.",
        pricingInfo: "Pabbly Connect offers straightforward pricing with an emphasis on unlimited usage across all plans. The Starter plan costs $49 per month (billed annually at $588) and includes unlimited workflows, unlimited tasks, basic support, and access to most integrations. The Pro plan at $99 per month (billed annually at $1,188) adds advanced features including team collaboration, workflow sharing, priority support, and access to premium integrations. The Enterprise plan at $199 per month (billed annually at $2,388) provides additional capabilities such as API access, webhook support, dedicated account management, and custom integration development. All plans allow unlimited users within the organization to access and benefit from the automations, eliminating per-user fees common in competing platforms. Pabbly offers a 14-day free trial of paid plans and provides a limited free tier supporting up to 5 tasks per day for evaluation purposes. Monthly billing options are available at approximately 20% higher rates than annual commitments. For customers requiring custom solutions or extensive implementation assistance, Pabbly offers professional services at additional cost, with pricing based on scope and complexity. The company provides special pricing for educational institutions and non-profit organizations upon request.",
        videoUrls: "https://www.youtube.com/watch?v=HRQqFGSrWEw",
        hasTrial: true
      }
    },
    {
      externalUrl: "https://www.decisions.com",
      data: {
        name: "Decisions",
        description: "Advanced business process automation platform with AI capabilities for creating, visualizing, and managing complex workflows and decision logic.",
        price: 50000,
        category: "automation",
        imageUrl: "https://decisions.com/wordpress/wp-content/themes/decisions/assets/images/logo.svg",
        tags: "business process management, workflow automation, decision rules, form builder, enterprise automation",
        advantages: "Powerful rules engine for complex logic, No-code and low-code development options, Visual flow designer for processes, Enterprise-grade security and integration, Flexible deployment options",
        disadvantages: "Enterprise pricing model, Steep learning curve for advanced features, Requires technical implementation team, Complex deployment compared to SaaS tools, Primarily designed for large organizations",
        detailInfo: "Decisions is a comprehensive business process automation platform that enables organizations to design, implement, and manage complex workflows and decision logic through a combination of no-code visual tools and advanced capabilities. The platform is designed to handle sophisticated enterprise requirements while remaining accessible to business analysts and process owners. At the core of Decisions is its dual approach to automation, combining a powerful workflow engine with an advanced rules system. The workflow engine allows users to design end-to-end processes using an intuitive visual designer, connecting different steps, systems, and people in orchestrated sequences. The rules engine enables the definition of complex decision logic, calculations, and conditions that govern process behavior, with support for rule flows, decision tables, and computational formulas. The platform includes a sophisticated forms designer that allows users to create interactive interfaces for data collection and user interaction, with features like dynamic fields, validation rules, and responsive layouts that adapt to different devices. A key differentiator is Decisions' flexibility in handling complex data operations, with capabilities for data transformation, validation, enrichment, and analysis built into the platform's core functionality. The system provides robust integration capabilities through pre-built connectors, REST API support, database connections, and file system operations, enabling workflows to exchange data with existing enterprise systems and external services. Decisions offers comprehensive reporting and analytics tools that provide visibility into process performance, bottlenecks, compliance, and operational metrics through customizable dashboards and scheduled reports. The platform supports various deployment models including cloud-hosted SaaS, private cloud, and on-premises installations, accommodating different security, compliance, and infrastructure requirements. Advanced features include version control for workflows and rules, testing and debugging tools, and environment management for development/test/production scenarios, supporting enterprise software development practices. Decisions serves mid-sized to large organizations across industries including financial services, healthcare, manufacturing, and government, with particular strength in regulated environments with complex operational requirements and decision-making needs.",
        pricingInfo: "Decisions offers enterprise pricing based on deployment model, functionality, and organizational scale. Cloud-based implementations typically start at $50,000 annually for departmental deployments and range to $250,000+ for enterprise-wide implementations with comprehensive capabilities. On-premises and private cloud deployments generally involve perpetual licensing starting at $100,000+ with annual maintenance fees of approximately 20% of the license cost. The platform's pricing structure considers factors including user types (administrators, developers, end users), process complexity, transaction volumes, and required modules. Implementation services, which include solution design, development assistance, training, and deployment support, typically range from $25,000-$150,000+ depending on project scope and complexity. Decisions offers a modular approach allowing organizations to start with core functionality and add additional capabilities (advanced rules, document generation, analytics) as needs evolve. The company provides proof-of-concept engagements for qualified prospects, allowing organizations to validate the platform's capabilities with their specific requirements before full investment. Volume discounts and multi-year agreements are available for larger implementations. Educational institutions and government agencies may qualify for special pricing programs.",
        videoUrls: "https://www.youtube.com/watch?v=6wRkZ-SxQcQ",
        hasTrial: false
      }
    }
  ]

  try {
    for (const product of automationProducts) {
      // Check if product already exists based on externalUrl
      const existingProduct = await prisma.product.findFirst({
        where: { externalUrl: product.externalUrl }
      })

      if (existingProduct) {
        // Update existing product
        await prisma.product.update({
          where: { id: existingProduct.id },
          data: product.data
        })
        console.log(`✅ Updated product: ${product.data.name}`)
      } else {
        // Create new product
        await prisma.product.create({
          data: {
            externalUrl: product.externalUrl,
            ...product.data
          }
        })
        console.log(`✅ Created new product: ${product.data.name}`)
      }
    }
    console.log('✨ All automation and workflow products (batch 4) have been stored in the database!')
  } catch (error) {
    console.error('❌ Error storing products:', error)
  } finally {
    await prisma.$disconnect()
  }
}

updateOrCreateProducts() 