import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

// This script will add more automation and workflow AI tools to the database
async function updateOrCreateProducts() {
  console.log('Saving automation and workflow AI tools (batch 3) to database...')

  // Array of automation and workflow products to add or update
  const automationProducts = [
    {
      externalUrl: "https://www.jitterbit.com",
      data: {
        name: "Jitterbit",
        description: "AI-powered integration platform that automates data flows and connects applications, APIs, and systems across enterprises.",
        price: 25000,
        category: "automation",
        imageUrl: "https://www.jitterbit.com/wp-content/uploads/2023/06/jitterbit-logo-color.svg",
        tags: "data integration, API management, enterprise automation, iPaaS, workflow automation",
        advantages: "Codeless integration builder, Pre-built connectors for 1,000+ systems, AI-powered data mapping and transformation, Real-time and batch processing, Comprehensive API management",
        disadvantages: "Enterprise pricing model, Technical expertise required for complex scenarios, Limited free tier functionality, Implementation complexity for large-scale deployments, Some advanced features require professional services",
        detailInfo: "Jitterbit is an enterprise-grade Integration Platform as a Service (iPaaS) that enables organizations to connect applications, data, and APIs without extensive coding. The platform's Harmony integration hub serves as the central control center for managing all integration processes across an organization. At the core of Jitterbit is its AI-powered integration engine, which automates key aspects of the integration process including connection configuration, data mapping, and transformation logic. The platform's visual, low-code interface allows business analysts and technical users alike to design integration workflows using a drag-and-drop approach, significantly reducing the time and specialized skills required compared to traditional integration methods. Jitterbit offers a comprehensive library of pre-built connectors for popular enterprise applications (Salesforce, SAP, NetSuite, etc.), cloud services, databases, and industry-specific systems, enabling rapid connectivity to most common business systems. For custom or specialized endpoints, the platform provides tools to create custom connectors using its API framework. A standout feature is Jitterbit's AI Integration Assistant, which analyzes source and target systems to automatically suggest optimal data mappings and transformation rules, dramatically speeding up one of the most time-consuming aspects of integration development. The platform includes robust capabilities for data quality management, error handling, and monitoring, ensuring that integrations remain reliable in production environments. For organizations with API-centric strategies, Jitterbit's API Manager allows teams to design, build, publish, and manage APIs across their lifecycle, extending the value of existing applications and data. Jitterbit serves customers across industries including healthcare, manufacturing, financial services, and retail, with particular strength in complex scenarios requiring real-time integration across multiple systems.",
        pricingInfo: "Jitterbit offers tiered pricing based on integration complexity, volume, and required capabilities. Standard plans for basic integration needs typically start at $20,000-$30,000 annually, providing core connectivity features, limited endpoints, and basic support. Professional plans for mid-sized organizations with moderate integration requirements range from $30,000-$75,000 per year, adding features like advanced transformations, API management, and expanded connector access. Enterprise plans for organizations with complex, mission-critical integration needs start at $75,000+ annually and include advanced features like high availability, dedicated environments, premium support, and unlimited endpoints. Implementation services, which include solution design, development assistance, and training, typically range from $15,000-$50,000+ depending on project complexity. Jitterbit structures contracts with initial terms of 12-36 months, with most customers opting for multi-year agreements. The company offers a limited free trial environment for evaluation purposes, but functionality is restricted compared to production plans.",
        videoUrls: "https://www.youtube.com/watch?v=LOeZHRTuN-E",
        hasTrial: true
      }
    },
    {
      externalUrl: "https://www.process.st",
      data: {
        name: "Process Street",
        description: "AI-enhanced workflow management platform that automates documented procedures, checklists, and recurring business processes.",
        price: 1188,
        category: "automation",
        imageUrl: "https://process.st/wp-content/uploads/2022/04/process-street-logo.svg",
        tags: "workflow automation, process documentation, SOP management, checklists, business operations",
        advantages: "No-code workflow builder, AI-powered workflow recommendations, Conditional logic and branching, Rich integrations with business tools, Detailed analytics and reporting",
        disadvantages: "Limited customization for complex workflows, Basic free tier with restricted features, Steeper learning curve for advanced functionality, Limited document management capabilities, Mobile app with fewer features than web version",
        detailInfo: "Process Street is a workflow management platform designed to help teams document, automate, and track recurring processes and procedures. The platform combines the functionality of traditional documentation tools with active workflow execution capabilities, enabling organizations to transform static standard operating procedures (SOPs) into interactive, actionable checklists that teams can follow and managers can monitor. At the heart of Process Street is its intuitive workflow editor, which allows users to create detailed process templates using a drag-and-drop interface. These templates can include text instructions, embedded media, form fields for data collection, approval gates, and conditional logic that adapts the workflow based on user inputs or system data. The platform's AI assistant analyzes existing workflows and suggests improvements based on best practices, identifying bottlenecks, redundant steps, or opportunities for automation. When a process needs to be executed, users can create a run from any template, assigning tasks to team members and setting due dates. The system automatically notifies participants at each stage, collects necessary information, and tracks progress in real-time. Process Street's integration capabilities allow workflows to connect with other business tools (CRM, project management, communication platforms, etc.), enabling the automatic transfer of data between systems and triggering actions in external applications. The platform includes robust reporting features that provide insights into process performance, compliance rates, completion times, and user activity, helping organizations identify opportunities for process optimization. Process Street serves customers across industries including professional services, healthcare, finance, and manufacturing, with particular strength in use cases involving compliance, onboarding, client management, and operational procedures.",
        pricingInfo: "Process Street offers several pricing tiers based on features and organizational needs. The Basic plan costs $99 per month (billed annually at $1,188) for up to 5 users and includes core workflow functionality, basic integrations, and reporting. The Professional plan at $499 per month (billed annually at $5,988) accommodates unlimited members and adds advanced features like conditional logic, role-based permissions, and API access. The Enterprise plan with custom pricing includes premium features such as advanced security controls, dedicated support, custom integrations, and enhanced compliance capabilities. All paid plans offer unlimited active workflows and workflow runs. Process Street also offers a limited free plan that includes up to 5 workflows and basic features, suitable for small teams or individuals looking to evaluate the platform. Implementation assistance and training packages are available as add-ons, ranging from $1,000-$5,000 depending on the level of support required. The company provides monthly billing options at a higher rate than annual commitments.",
        videoUrls: "https://www.youtube.com/watch?v=98qKRlgcUUk",
        hasTrial: true
      }
    },
    {
      externalUrl: "https://www.zenhub.com",
      data: {
        name: "ZenHub",
        description: "AI-powered project management platform for software teams that automates workflows, planning, and reporting within GitHub.",
        price: 1200,
        category: "automation",
        imageUrl: "https://www.zenhub.com/wp-content/uploads/2021/05/zenhub-color-horizontal.svg",
        tags: "agile project management, GitHub integration, sprint planning, software development, team productivity",
        advantages: "Native GitHub integration, AI sprint planning and automation, Real-time roadmapping, Automated task tracking, Team velocity and burndown analytics",
        disadvantages: "Primarily focused on GitHub users, Learning curve for non-technical users, Some features require GitHub Enterprise, Limited customization for Kanban boards, Premium pricing compared to basic project tools",
        detailInfo: "ZenHub is a project management platform built specifically for software development teams using GitHub. Unlike traditional project management tools that require context switching between repositories and management interfaces, ZenHub embeds directly within the GitHub interface, creating a seamless experience where developers can manage tasks without leaving their code environment. The platform enhances GitHub's native capabilities with a comprehensive set of agile project management features including customizable Kanban boards, sprint planning tools, roadmapping, and automated reporting. A key differentiator is ZenHub's AI-powered sprint planning assistant, which analyzes historical team performance, issue complexity, and dependencies to suggest optimal sprint allocations, helping teams commit to realistic workloads. The platform's automated workflows feature allows teams to create rule-based automations that update issue statuses, assign team members, apply labels, and trigger notifications based on specified conditions, reducing manual administrative work. ZenHub's roadmapping capability connects strategic planning with tactical execution, allowing teams to visualize how daily work connects to larger initiatives and product goals. The platform provides comprehensive analytics including velocity tracking, burndown charts, cumulative flow diagrams, and release reports, giving teams and stakeholders visibility into project health and team performance. ZenHub facilitates cross-team collaboration through multi-repository boards that can combine issues from different projects, enabling coordination across complex organizations while maintaining appropriate access controls. The platform integrates with other development tools beyond GitHub, including Slack, Microsoft Teams, and various CI/CD systems, creating a connected ecosystem for software delivery. ZenHub primarily serves software development teams across organizations of all sizes, from startups to enterprises, with particular strength in organizations committed to agile methodologies.",
        pricingInfo: "ZenHub offers tiered pricing based on team size and required features. The Growth plan costs $10 per user per month (billed annually at $120 per user) and includes core features like boards, sprints, reporting, and basic automations. The Enterprise plan at $12.50 per user per month (billed annually at $150 per user) adds advanced features including enhanced security controls, priority support, custom automation workflows, and advanced roadmapping capabilities. For GitHub Enterprise users, ZenHub offers ZenHub Enterprise with on-premises or private cloud deployment options at custom pricing, typically starting at $25,000 annually depending on organization size. All plans include unlimited repositories and projects. ZenHub provides a free tier for public repositories and small teams of up to 5 users, allowing teams to evaluate the platform before committing to a paid plan. Academic and open-source discounts are available upon request. The company offers monthly billing options at approximately 20% higher rates than annual commitments.",
        videoUrls: "https://www.youtube.com/watch?v=Bwaluj-3P6E",
        hasTrial: true
      }
    },
    {
      externalUrl: "https://www.ntaskmanager.com",
      data: {
        name: "nTask",
        description: "AI-enhanced project and task management platform that automates workflows, resource allocation, and team collaboration.",
        price: 96,
        category: "automation",
        imageUrl: "https://ntaskmanager.com/wp-content/uploads/2022/03/ntask-logo-blue.svg",
        tags: "project management, task automation, team collaboration, time tracking, workflow management",
        advantages: "All-in-one project management solution, Native time tracking functionality, Risk assessment and issue management, Meeting management with action items, Affordable pricing for small teams",
        disadvantages: "Limited advanced automation capabilities, Fewer integrations than enterprise platforms, Mobile app with reduced functionality, Basic reporting compared to specialized tools, Learning curve for all available features",
        detailInfo: "nTask is a comprehensive project management platform designed to help teams plan, organize, and track work across multiple projects and workflows. The platform combines task management, project planning, team collaboration, time tracking, and risk management into a unified interface, eliminating the need to switch between multiple tools. At the core of nTask is its task management system, which allows users to create, assign, and track tasks with customizable statuses, priorities, dependencies, and due dates. Tasks can be organized into projects and viewed through multiple perspectives including list views, Kanban boards, calendar views, and Gantt charts, accommodating different work styles and project methodologies. The platform's workflow automation engine enables teams to create customized workflows that automatically update task statuses, notify team members, and trigger follow-up actions based on predefined conditions, reducing manual administrative work. nTask offers built-in time tracking functionality that allows team members to record hours spent on tasks, generating accurate timesheets for billing, productivity analysis, and resource allocation. The platform includes dedicated modules for meeting management, risk assessment, and issue tracking, expanding its utility beyond basic project management. Meeting tools allow teams to schedule sessions, create agendas, record minutes, assign action items, and track follow-ups, creating accountability for meeting outcomes. The risk management module helps teams identify potential obstacles, assess their impact and likelihood, and develop mitigation strategies, improving project resilience. nTask's collaboration features include team chat, file sharing, comments, and @mentions, facilitating communication within the context of specific tasks or projects. The platform integrates with popular tools including Slack, Microsoft Teams, Google Calendar, and various email clients, connecting nTask with existing workflow systems. nTask serves customers across industries including marketing agencies, software development teams, consulting firms, and professional services organizations, with particular appeal to small and mid-sized businesses seeking comprehensive project management capabilities at an accessible price point.",
        pricingInfo: "nTask offers tiered pricing based on features and team requirements. The Premium plan costs $8 per user per month (billed annually at $96 per user) and includes core features like unlimited tasks and projects, Gantt charts, issue tracking, risk management, and basic reporting. The Business plan at $12 per user per month (billed annually at $144 per user) adds advanced features including custom fields, enhanced security controls, priority support, and advanced reporting capabilities. The Enterprise plan with custom pricing includes premium features such as dedicated account management, custom onboarding, API access, and enhanced compliance capabilities. nTask also offers a limited free plan that supports up to 5 team members, 100 MB storage, and basic task management features, suitable for individuals or very small teams. The platform provides a 14-day free trial of paid plans, allowing teams to evaluate premium features before committing. Monthly billing options are available at approximately 20% higher rates than annual commitments. For larger organizations, nTask offers volume discounts on annual subscriptions.",
        videoUrls: "https://www.youtube.com/watch?v=5CkWQfh-Ad4",
        hasTrial: true
      }
    },
    {
      externalUrl: "https://www.pneumatic.app",
      data: {
        name: "Pneumatic",
        description: "AI-powered workflow automation platform designed for human-in-the-loop processes and approval workflows across teams and systems.",
        price: 1788,
        category: "automation",
        imageUrl: "https://pneumatic.app/wp-content/uploads/2023/02/pneumatic-logo.svg",
        tags: "workflow automation, approval processes, human-in-the-loop, form automation, business process management",
        advantages: "Intuitive visual workflow builder, AI-enhanced form processing, Specialized for approval workflows, End-user friendly interface, Detailed audit trails and compliance",
        disadvantages: "Limited third-party integrations compared to competitors, Newer platform with smaller community, Complex pricing structure, Advanced analytics require higher tier plans, Limited customization for enterprise-specific needs",
        detailInfo: "Pneumatic is a workflow automation platform specifically designed for human-centric processes that require coordination across multiple participants, approvals, and systems. Unlike purely technical automation tools, Pneumatic focuses on workflows where human judgment, decisions, and actions are essential parts of the process. The platform's core functionality centers around its visual workflow builder, which allows users to design multi-step processes using an intuitive drag-and-drop interface. Workflows can include conditional logic, parallel processing paths, approval gates, form collection points, and integration touchpoints with external systems. A key differentiator is Pneumatic's AI-enhanced forms processing capability, which can extract and validate information from submitted documents, detect anomalies, and route items to appropriate reviewers based on content analysis. The platform excels at managing approval processes, with flexible configurations for sequential, parallel, and conditional approvals, delegation rules, and reminder systems to prevent bottlenecks. For end users initiating requests, Pneumatic provides a clean, intuitive portal where they can submit new requests, track progress, respond to questions, and view historical submissions without needing access to the full workflow management system. The platform maintains comprehensive audit trails that document every action, decision, and modification throughout a process, supporting compliance requirements and providing valuable insights for process improvement. Pneumatic includes reporting and analytics tools that highlight process performance metrics, bottlenecks, and efficiency opportunities, helping organizations continuously optimize their workflows. The platform offers integration capabilities through webhooks, APIs, and pre-built connectors to common business systems, allowing workflows to exchange data with external applications when necessary. Pneumatic serves customers across industries including financial services, healthcare, government, and professional services, with particular strength in regulated environments where process consistency, documentation, and compliance are critical requirements.",
        pricingInfo: "Pneumatic offers tiered pricing based on workflow volume, complexity, and required capabilities. The Team plan costs $149 per month (billed annually at $1,788) and supports up to 25 active workflows, 5 administrators, unlimited workflow participants, and core features including visual workflow design, forms processing, approval management, and basic reporting. The Business plan at $349 per month (billed annually at $4,188) increases capacity to 100 active workflows, 15 administrators, and adds features like advanced conditional logic, API access, priority support, and enhanced security controls. The Enterprise plan with custom pricing provides unlimited workflows, administrators, and premium features including advanced analytics, dedicated support, custom integrations, and enhanced compliance capabilities. All plans include unlimited workflow runs and participants, making pricing predictable regardless of organization size. Pneumatic offers a 14-day free trial of all plans and provides a limited free tier supporting up to 3 active workflows and basic features for small teams or evaluation purposes. Implementation services and training packages are available as add-ons, with pricing based on scope and complexity. Monthly billing options are available at approximately 20% higher rates than annual commitments.",
        videoUrls: "https://www.youtube.com/watch?v=YQmqBUFtMzA",
        hasTrial: true
      }
    },
    {
      externalUrl: "https://www.reclaim.ai",
      data: {
        name: "Reclaim.ai",
        description: "AI time management assistant that automatically schedules tasks, meetings, and personal time in your calendar based on priorities and preferences.",
        price: 108,
        category: "automation",
        imageUrl: "https://assets-global.website-files.com/61fd684f8d5599374eb6ce93/6208c95b87dc5f7b65fa1c3a_reclaim-logo-gradient.svg",
        tags: "time management, calendar automation, task scheduling, productivity, work-life balance",
        advantages: "Automatic task scheduling and rescheduling, Smart meeting scheduling across teams, Habit building for regular activities, Work-life balance protection, Calendar analytics and insights",
        disadvantages: "Primary Google Calendar integration (limited Microsoft support), Learning curve for optimal configuration, Some features only available in higher tiers, May over-schedule without careful setup, Limited customization for complex scheduling rules",
        detailInfo: "Reclaim.ai is an intelligent calendar assistant that helps knowledge workers optimize their time by automatically scheduling and protecting time for their most important work. The platform integrates with calendar systems and uses artificial intelligence to find and block optimal slots for different types of activities based on priorities, preferences, and work patterns. At the core of Reclaim is its task scheduling capability, which allows users to create tasks with estimated durations, deadlines, and priority levels. The system then automatically finds and reserves time on the calendar to complete these tasks, intelligently placing them around existing meetings and commitments. As circumstances change—meetings are added or canceled, deadlines shift, or priorities evolve—Reclaim automatically reschedules tasks to ensure they remain viable in the updated context. The platform's Smart 1:1 feature streamlines the scheduling of recurring one-on-one meetings, automatically finding optimal times that work for all participants and adjusting when conflicts arise, eliminating the back-and-forth typically required for scheduling. Reclaim's Habits functionality helps users build consistency for regular activities like deep work, personal development, or exercise by automatically scheduling and protecting recurring blocks of time for these important but often neglected priorities. A significant differentiator is Reclaim's focus on work-life balance, with features that automatically block personal time, enforce boundaries between work and personal activities, and ensure users don't get overbooked. The platform provides comprehensive analytics on how time is spent across different types of activities, meeting load, focus time availability, and scheduling patterns, giving users insights to make better decisions about their time investments. Reclaim integrates primarily with Google Calendar, with more limited support for Microsoft Calendar, and connects with task management tools including Jira, Asana, and Todoist to import tasks for scheduling. The platform serves individual knowledge workers, teams, and organizations across industries, with particular appeal to managers, executives, engineers, and other professionals with high demands on their time and significant calendar management challenges.",
        pricingInfo: "Reclaim.ai offers tiered pricing based on features and capabilities. The Starter plan is free and includes basic scheduling for up to 3 tasks per week with limited customization. The Basic plan costs $9 per user per month (billed annually at $108 per user) and includes unlimited tasks, habits, and smart 1:1s with standard optimization features. The Pro plan at $12 per user per month (billed annually at $144 per user) adds advanced features including calendar analytics, team scheduling insights, enhanced integrations, and priority support. The Team plan with custom pricing includes premium features such as admin controls, organization-wide analytics, custom integrations, and dedicated account management. All paid plans offer a 14-day free trial period with full access to features. Reclaim provides monthly billing options at approximately I5% higher rates than annual commitments. For larger organizations, volume discounts are available on annual subscriptions. The company offers educational and non-profit discounts upon request.",
        videoUrls: "https://www.youtube.com/watch?v=J7pKj3GH7N0",
        hasTrial: true
      }
    },
    {
      externalUrl: "https://www.flowmind.ai",
      data: {
        name: "FlowMind",
        description: "AI-powered workflow design assistant that helps teams visualize, optimize and automate business processes with intuitive diagramming.",
        price: 199,
        category: "automation",
        imageUrl: "https://static.wixstatic.com/media/61cf16_ca1a0b5b64dd4a8c83e57aa9dd2d3c54~mv2.png/v1/fill/w_314,h_82,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/FlowMind%20-Logo.png",
        tags: "process mapping, workflow design, business process modeling, BPMN, AI process optimization",
        advantages: "AI-generated process diagrams from text descriptions, Automatic process optimization suggestions, Collaborative real-time editing, BPMN 2.0 standard compliance, Process simulation capabilities",
        disadvantages: "Limited direct integrations with execution systems, Newer platform with evolving features, Enterprise features require higher tier plans, Learning curve for advanced modeling, Focused more on design than execution",
        detailInfo: "FlowMind is an intelligent process modeling platform that combines traditional business process mapping capabilities with artificial intelligence to help organizations design, document, analyze, and optimize their operational workflows. The platform reimagines how teams create process diagrams, allowing users to generate visualizations from simple text descriptions rather than manually constructing them from scratch. At the core of FlowMind is its AI process generator, which transforms natural language descriptions of workflows into structured BPMN (Business Process Model and Notation) diagrams. Users can describe a process in conversational language, and the system automatically creates a professionally formatted process map with appropriate symbols, connections, and layout. This dramatically reduces the time required to document processes and makes process modeling accessible to non-technical users. The platform's process intelligence engine analyzes existing workflows to identify potential bottlenecks, redundancies, and optimization opportunities, suggesting specific improvements to enhance efficiency and effectiveness. FlowMind includes sophisticated simulation capabilities that allow teams to model different scenarios, test process changes, and predict outcomes before implementation, reducing the risk of operational disruptions. The platform supports collaborative editing, enabling multiple users to work on process diagrams simultaneously with real-time updates and commenting features that facilitate team input and approval. FlowMind adheres to BPMN 2.0 standards, ensuring that process documentation follows industry best practices and can be understood across organizations and systems. The platform includes a comprehensive repository for organizing and managing process documentation, with version control, search capabilities, and access controls to maintain process governance. While primarily focused on process design and optimization, FlowMind offers export capabilities and APIs that allow integration with process automation and execution systems when implementation is required. FlowMind serves customers across industries including manufacturing, financial services, healthcare, and professional services, with particular appeal to organizations undertaking digital transformation initiatives, implementing continuous improvement programs, or working to standardize operational procedures.",
        pricingInfo: "FlowMind offers tiered pricing based on features, users, and usage requirements. The Professional plan costs $199 per month for up to 5 users (effectively $39.80 per user) and includes core features like AI-powered process generation, collaboration tools, simulation capabilities, and standard support. The Business plan at $499 per month for up to 15 users adds advanced features including enhanced process analytics, priority support, expanded storage, and additional export options. The Enterprise plan with custom pricing provides unlimited users and premium features such as dedicated account management, custom integrations, advanced security controls, and on-premises deployment options. All plans include unlimited process diagrams within storage limitations. FlowMind offers a limited free tier that supports basic process modeling for individuals or small teams with restricted features and diagram limits. The platform provides a 14-day free trial of paid plans for evaluation purposes. Annual commitment discounts of approximately 20% are available on all plans. For educational institutions and non-profit organizations, FlowMind offers special pricing upon request.",
        videoUrls: "https://www.youtube.com/watch?v=jHZ8iDUqhMQ",
        hasTrial: true
      }
    },
    {
      externalUrl: "https://www.processgpt.ai",
      data: {
        name: "ProcessGPT",
        description: "AI platform that analyzes, optimizes and automates business processes by understanding process documentation and executing workflow improvements.",
        price: 10000,
        category: "automation",
        imageUrl: "https://processgpt.ai/wp-content/uploads/2023/09/processgpt-logo.png",
        tags: "process automation, AI workflow analysis, business process improvement, intelligent automation, digital transformation",
        advantages: "Natural language process understanding, Automated process discovery and mapping, Intelligent automation recommendations, Integration with existing systems, Continuous process monitoring and adaptation",
        disadvantages: "Enterprise-level pricing, Significant implementation effort, Requires quality process documentation, Limited pre-built process templates, Best results require process maturity",
        detailInfo: "ProcessGPT is an advanced business process intelligence platform that applies large language model capabilities to the domain of process analysis, optimization, and automation. The platform goes beyond traditional process mining and automation tools by understanding the context, intent, and nuances of business processes described in natural language, then translating that understanding into actionable insights and automated workflows. At the core of ProcessGPT is its ability to ingest and comprehend various forms of process documentation—including written procedures, flowcharts, recorded process walkthroughs, and system logs—creating a comprehensive digital representation of how work happens within an organization. The platform's process discovery functionality can also analyze system interactions and user behaviors to identify undocumented processes and variations from standard procedures. ProcessGPT's intelligence engine evaluates processes against industry best practices, internal benchmarks, and operational goals to identify improvement opportunities, inefficiencies, compliance risks, and automation candidates. For processes identified as automation candidates, the platform can generate implementation plans ranging from simple robotic process automation (RPA) scripts to complex intelligent workflows that incorporate decision logic, human touchpoints, and system integrations. A key differentiator is ProcessGPT's ability to continuously monitor process performance and adapt automation as conditions change, creating self-optimizing workflows that improve over time rather than static automation that quickly becomes outdated. The platform includes simulation capabilities that allow organizations to model the impact of process changes before implementation, reducing risk and validating expected benefits. ProcessGPT integrates with leading enterprise systems including ERP, CRM, and ITSM platforms, as well as existing automation tools, creating a unified layer for process intelligence and enhancement. The platform serves mid-sized to large enterprises across industries including financial services, healthcare, manufacturing, and professional services, with particular strength in complex operational environments with significant process variation and optimization opportunities.",
        pricingInfo: "ProcessGPT offers enterprise pricing based on the scope of implementation, process complexity, and organizational scale. Custom packages typically start at $10,000 per month ($120,000 annually) for focused deployments covering specific process domains or departments. Organization-wide implementations for mid-sized enterprises range from $25,000-$50,000 per month, while large enterprise deployments with comprehensive capabilities can exceed $100,000 per month. Implementation services, which include process discovery workshops, system integration, custom model training, and user onboarding, typically range from $50,000-$250,000 depending on scope and complexity. ProcessGPT structures its contracts with initial terms of 12-36 months, with most customers opting for multi-year agreements as the platform becomes more valuable over time with accumulated process knowledge. The company offers a proof-of-concept program for qualified prospects, allowing organizations to validate the platform's capabilities with their specific processes before full implementation. Volume discounts and outcome-based pricing components are available for larger deployments, with some contracts including performance incentives tied to documented process improvements.",
        videoUrls: "https://www.youtube.com/watch?v=L5MpCrLkEJw",
        hasTrial: false
      }
    }
  ]

  try {
    for (const product of automationProducts) {
      // Check if product already exists based on externalUrl
      const existingProduct = await prisma.product.findFirst({
        where: { externalUrl: product.externalUrl }
      })

      if (existingProduct) {
        // Update existing product
        await prisma.product.update({
          where: { id: existingProduct.id },
          data: product.data
        })
        console.log(`✅ Updated product: ${product.data.name}`)
      } else {
        // Create new product
        await prisma.product.create({
          data: {
            externalUrl: product.externalUrl,
            ...product.data
          }
        })
        console.log(`✅ Created new product: ${product.data.name}`)
      }
    }
    console.log('✨ All automation and workflow products (batch 3) have been stored in the database!')
  } catch (error) {
    console.error('❌ Error storing products:', error)
  } finally {
    await prisma.$disconnect()
  }
}

updateOrCreateProducts() 