name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  web:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build:ci
        env:
          NEXT_PUBLIC_API_BASE_URL: http://localhost:3000
          NEXT_PUBLIC_BASE_URL: http://localhost:3000
          EMAIL_TOKEN_SECRET: dummysecretfortests
          PYTHON_API_URL: http://localhost:3000/api/python

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Start server
        run: npm run start:ci &

      - name: Wait for server
        run: npx wait-on http://localhost:3000 --timeout 60000

      - name: Smoke tests
        run: npm run test:smoke
        env:
          E2E_BASE_URL: http://localhost:3000

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          if-no-files-found: ignore

